# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TVSIpZ8FMKO7UF3EoSEzrkXxGb1WMUH8
"""

x_0 = 1
x_1 = 1
x_2 = 0
sum = 0
while x_2 <= 4*10**6:
  x_2 = x_1 + x_0
  x_0 = x_1
  x_1 = x_2
  if (x_2 % 2) == 0:
    sum+=x_2

